config/routes.rb
RayindaBlog::Application.routes.draw do

  
  mount Ckeditor::Engine => '/ckeditor'

  get "log_in" => "sessions#new", :as => "log_in"
  get "log_out" => "sessions#destroy", :as => "log_out"
  get "sign_up" => "users#new", :as => "sign_up" 
  
  get "about" => "about", controller: :about, :as => "about" 
  get "contact" => "contact", contoller: :contact, :as => "contact" 

  get "autocomplete_tag_name" => "author/posts#autocomplete_tag_name", :as => "autocomplete_tag_name"
  
  get "search" => "main#search", :as => "search"
  
  resources :sessions, :only => [:new, :create, :destroy]
  resources :users

  root :to => "main#index"
  
  namespace :admin do
    resources :posts, :users, :categories
  end
    
  namespace :user do
    resource :membership_info, only: [:show, :edit, :update], controller: :membership 
    resource :dashboard, only: [:show], controller: :dashboard
  end
  
  resources :authors, only: [:show, :index] do
    resources :posts, only: [:show, :index], controller: :author_posts
  end
  
  namespace :author do
    resources :posts, as: :myposts, controller: :posts do
      get :autocomplete_tag_name, :on => :collection
      resources :comments, only: :destroy
    end
  end
  resources :posts do
    resources :comments
  end
  resources :categories do
    resources :posts, controller: :category_posts, only: [:index, :show]
  end
  namespace :tag do
    resources :posts, only: [:index], controller: :tags
  end
  
end

app/views/shared/_admin_dashboard.html.erb
<li class="dropdown" id="menu1">
  <a class="dropdown-toggle" data-toggle="dropdown" href="#menu1">
    <%= (t "general.manage") %>
    <b class="caret"></b>
  </a>
  <ul class="dropdown-menu">
    <li><%= link_to (t "general.allposts", :count => Post.count.to_s), admin_posts_path %></li>
    <li><%= link_to (t "general.allusers", :count => User.count.to_s), admin_users_path %></li>
    <li class="divider"></li>
    <li><%= link_to (t "general.allcategories", :count => Category.count.to_s), admin_categories_path %></li>
  </ul>
</li>

app/views/shared/_author_dashboard.html.erb
<li class="dropdown" id="menu2">
  <a class="dropdown-toggle" data-toggle="dropdown" href="#menu2">
    <%= (t "general.posts") %>
    <b class="caret"></b>
  </a>
  <ul class="dropdown-menu">
    <li><%= link_to (t "general.myposts", :count => current_user.posts.count.to_s), author_myposts_path%></li>
    <li><%= link_to (t "new post"), new_author_mypost_path %></li>
    <li class="divider"></li>
    <li><%= link_to (t "membership"), user_membership_info_path %></li>
  </ul>
</li>

app/views/shared/_notice.html.erb
<% if flash[:notice] %>
  <div class="alert alert-info">
    <a class="close" data-dismiss="alert">×</a>
    <%= content_tag :div, flash[:notice] %>
  </div>
<% end %>

<% if flash[:alert] %>
  <div class="alert alert-error">
    <a class="close" data-dismiss="alert">×</a>
    <%= content_tag :div, flash[:alert] %>
  </div>
<% end %>