config/routes.rb
RayindaBlog::Application.routes.draw do

  
  mount Ckeditor::Engine => '/ckeditor'

  get "log_in" => "sessions#new", :as => "log_in"
  get "log_out" => "sessions#destroy", :as => "log_out"
  get "sign_up" => "users#new", :as => "sign_up" 
  
  get "about" => "about", controller: :about, :as => "about" 
  get "contact" => "contact", contoller: :contact, :as => "contact" 

  get "autocomplete_tag_name" => "author/posts#autocomplete_tag_name", :as => "autocomplete_tag_name"
  
  get "search" => "main#search", :as => "search"
  
  resources :sessions, :only => [:new, :create, :destroy]
  resources :users

  root :to => "main#index"
  
  namespace :admin do
    resources :posts, :users, :categories
  end
    
  namespace :user do
    resource :membership_info, only: [:show, :edit, :update], controller: :membership 
    resource :dashboard, only: [:show], controller: :dashboard
  end
  
  resources :authors, only: [:show, :index] do
    resources :posts, only: [:show, :index], controller: :author_posts
  end
  
  namespace :author do
    resources :posts, as: :myposts, controller: :posts do
      get :autocomplete_tag_name, :on => :collection
      resources :comments, only: :destroy
    end
  end
  resources :posts do
    resources :comments
  end
  resources :categories do
    resources :posts, controller: :category_posts, only: [:index, :show]
  end
  namespace :tag do
    resources :posts, only: [:index], controller: :tags
  end
  
end

app/models/post.rb
class Post < ActiveRecord::Base

  belongs_to :user
  belongs_to :category

  has_many :comments, :dependent => :destroy

  attr_accessible :category_id, :title, :body, :spot, :tag_list, :published
  attr_accessor :tag

  validates :title, :presence => true
  validates :body, :presence => true
  validates_presence_of :published_at, :if => :published
  validates :user_id, :presence => true

  default_scope :order => 'posts.created_at DESC'
  
  acts_as_taggable  
  
  # Syntax highlight özelliği için başka yöntem yada gist kullanılacak.
  # before_save :render_body  
  
  def self.feed(last)
		self.where("created_at < ? ", last).order('created_at desc').limit(5)
	end

  def render_body
    require 'redcarpet'
    options = [:hard_wrap, :autolink, :no_intraemphasis, :fenced_code, :gh_blockcode]
    self.rendered_body = Redcarpet.new(self.body, *options).to_html
  end
  
  def is_author?
    author
  end
  def self.search(query)
    search_condition = "%" + query + "%"
    find(:all, :conditions => ['title LIKE ? OR body LIKE ?', search_condition, search_condition])
  end
  
end

app/controllers/admin/posts_controller.rb
class Admin::PostsController < Admin::BaseController

  before_filter :require_admin
  
  def index
    @posts = @post_status.page(params[:page]).per(5)
  end

  def show
    @post = @post_status.find(params[:id])
  end

  def edit
    @post = @post_status.find(params[:id])
    @available_categories = Category.all
  end

  def update
    @post = @post_status.find(params[:id])

    if @post.update_attributes(params[:post])
      redirect_to [:admin, @post], notice: 'Post was successfully updated.'
    else
      render action: "edit"
    end
  end

  def destroy
    @post = @post_status.find(params[:id]).destroy
    redirect_to admin_posts_url
  end

  def set_post

  end

end

app/controllers/author/comments_controller.rb
class Author::CommentsController < ApplicationController
  before_filter :require_author
  
  before_filter :find_current_post
  
  def destroy
    @post.comments.find(params[:id]).destroy
    redirect_to author_mypost_path(@post)
  end
  
  private
  def find_current_post
    @post = current_user.posts.find(params[:mypost_id])
    redirect_to root_path, :notice => "You are not authorized to access this page." and return if @post.nil?
  end
end

app/controllers/author/posts_controller.rb
class Author::PostsController < ApplicationController

  before_filter :require_author, :except => [:show, :index]

  def autocomplete_tag_name
    render json: Tag.where("name like '#{params[:q]}%'")
  end
  
  def index
    @posts = Post.where(:user_id => current_user.id).page(params[:page]).per(5)
  end

  def show
    @post = current_user.posts.find(params[:id])
  end

  def new
    @post = current_user.posts.new
    @available_categories = Category.all
  end

  def edit
    @post = current_user.posts.find(params[:id])
    @available_categories = Category.all
  end

  def create
    @post = current_user.posts.new(params[:post])
    @post.published_at = Time.now if @post.published
    if @post.save
      redirect_to author_mypost_path(@post), notice: 'Post was successfully created.'
    else
      render action: "new"
    end
  end

  def update
    @post = current_user.posts.find(params[:id])
    @post.published_at = Time.now if (params[:post][:published] && @post.published_at.nil?)
    if @post.update_attributes(params[:post])
      redirect_to author_mypost_path(@post), notice: 'Post was successfully updated.'
    else
      render action: "edit"
    end
  end

  def destroy
    current_user.posts.find(params[:id]).destroy
    redirect_to author_myposts_path, notice: 'The post was deleted successfully'
  end
end

app/views/author/posts/edit.html.erb
<script type="text/javascript" >
   $(document).ready(function() {
      $("#markItUp").markItUp(markDownSettings);
      $("#markItUp_spot").markItUp(htmlSettings);
   });
</script>
<div class="panel">
<%= form_for(@post, :url => author_mypost_path(@post)) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <div class="panel-title">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="panel-title">
    <%= f.label :category %><br />
    <%= f.select :category_id, options_from_collection_for_select(@available_categories, 'id', 'name') %>
  </div>
  <div class="panel-title">
    <%= f.label :body %><br />
    <div class="markDownEdit"><%= f.text_area :body, :id => "markItUp" %></div>
  </div>
  <div class="panel-title">
    <%= f.label :spot %><br />
    <%= f.text_area :spot, :id => "markItUp_spot" %>
  </div>
  <div class="panel-title">
    <%= f.label :tag_list %><br />
    <%= f.text_field :tag_list %>
  </div>
  <div class="panel-title">
    <%= f.label :published %><br />
    <%= f.check_box :published %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
  <% end %>
  <div class="panel-content">
    <%= link_to 'Show', author_mypost_path(@post) %> |
    <%= link_to 'Back', author_myposts_path %>
  </div>
</div>

app/views/author/posts/index.html.erb
<div class="articles">
<% @posts.each do |post| %>
	<div class="article">
	  <div class="article-cdt">
	    <div class="cat"><%= link_to post.category.try(:name), category_posts_path(post.category) %></div>
			<div class="date"><%= post.published_at.try(:strftime, '%d-%m-%y') %></div>
      <div class="tag"> <% post.tags.each do |tag|%><%= link_to tag.name, tag_posts_path(:tag => tag.name) %>
        <% end %>
      </div>
	    <div class="author"><%= link_to post.user.name, author_posts_path(post.user_id) %></div>
    </div>
	  <div class="article-title">
	    <h2><%= link_to post.title, author_mypost_path(post)%></h2>
	  </div>
		<div class="article-content">
		  <p>
		  <%= post.spot.html_safe %>
		  </p>
		</div>
		<div class="article-adv"> <span><%= link_to (t "more"), author_mypost_path(post), :class => "article-more" %></span> </div>
	</div>
<% end %>
</div>

<div class="article">
	<div class="article-cdt">
    <div class="tag"><%= paginate @posts%></div>
  </div>
</div>

app/views/author/posts/new.html.erb
<%= simple_form_for(@post, :url => author_myposts_path) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>
      <ul>
      <% @post.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <%= f.input :title, :input_html => { :class => "span8" }, :placeholder => "Title", :label => false %>
  <%= f.association :category, :class => "span6" %>
  <%= f.input :tag_list, :input_html => { :class => "span8" }, :placeholder => "Tag List", :label => false %>
  <%#= f.input :spot, :id => "markItUp_spot", :input_html => { :class => "span8", :rows => "10" }, :placeholder => "Spot", :label => false %>
  <div class="wmd-panel">
    <div id="wmd-button-bar"></div>
    <%= f.input :spot, :input_html => {:id => "wmd-input", :class => "wmd-input span8", :rows => "10" }, :placeholder => "Spot", :label => false %>
  <div id="wmd-preview" class="wmd-panel wmd-preview span8 prettyprint"></div>
  </div>
  <div class="wmd-panel">
    <div id="wmd-button-bar-second"></div>
    <%= f.input :body, :input_html => {:id => "wmd-input-second", :class => "wmd-input span8" }, :placeholder => "Body", :label => false %>
  <div id="wmd-preview-second" class="wmd-panel wmd-preview span8 prettyprint"></div>
  </div>
  <%= f.input :published %>  
  <%= f.submit :class => 'btn-primary' %>  
<% end %>
<%= link_to (t "general.back"), author_myposts_path, :class => "btn btn-danger" %>

<script type="text/javascript" >
  $(document).ready(function() {
     var converter1 = Markdown.getSanitizingConverter();
     var editor1 = new Markdown.Editor(converter1);
     editor1.run();
     var converter2 = Markdown.getSanitizingConverter();
     var editor2 = new Markdown.Editor(converter2, "-second");
     editor2.run();
  });
</script>

app/views/author/posts/show.html.erb
<div class="articles">
  <div class="article">
	  <div class="article-title">
      <span class="article_cat"><%= link_to @post.category.try(:name), category_posts_path(@post.category) %></span>
	    <h2><%= @post.title %></h2>
	  </div>
		<div class="article-content">
		  <p>
      <%#= markdown(@post.rendered_body) %>  <!-- Burası markdown hisglight için gereklidir. -->
		  <%= @post.rendered_body %>
		  </p>
    </div>
        <div class="article-cdt">
			<div class="date"><%= @post.published_at.try(:strftime, '%d-%m-%y') %></div>
			<div class="tag"><% @post.tags.each do |tag|%><%= link_to tag.name, tag_posts_path(:tag => tag.name) %>
        <% end %></div>
	      <div class="author"><%= link_to @post.user.name, author_posts_path(@post.user_id) %></div>

  </div>
  </div>
  <div class="admlinks">
   <li><%= link_to (t "general.edit"), edit_author_mypost_path(@post) %></li>
   <li><%= link_to (t "general.back"), author_myposts_path %></li>
   <li><%= link_to (t "general.destroy"), author_mypost_path(@post), confirm: (t "general.Are you sure"),
    :method => :delete %></li>
    </div>
</div>