config/routes.rb
RayindaBlog::Application.routes.draw do

  
  mount Ckeditor::Engine => '/ckeditor'

  get "log_in" => "sessions#new", :as => "log_in"
  get "log_out" => "sessions#destroy", :as => "log_out"
  get "sign_up" => "users#new", :as => "sign_up" 
  
  get "about" => "about", controller: :about, :as => "about" 
  get "contact" => "contact", contoller: :contact, :as => "contact" 

  get "autocomplete_tag_name" => "author/posts#autocomplete_tag_name", :as => "autocomplete_tag_name"
  
  get "search" => "main#search", :as => "search"
  
  resources :sessions, :only => [:new, :create, :destroy]
  resources :users

  root :to => "main#index"
  
  namespace :admin do
    resources :posts, :users, :categories
  end
    
  namespace :user do
    resource :membership_info, only: [:show, :edit, :update], controller: :membership 
    resource :dashboard, only: [:show], controller: :dashboard
  end
  
  resources :authors, only: [:show, :index] do
    resources :posts, only: [:show, :index], controller: :author_posts
  end
  
  namespace :author do
    resources :posts, as: :myposts, controller: :posts do
      get :autocomplete_tag_name, :on => :collection
      resources :comments, only: :destroy
    end
  end
  resources :posts do
    resources :comments
  end
  resources :categories do
    resources :posts, controller: :category_posts, only: [:index, :show]
  end
  namespace :tag do
    resources :posts, only: [:index], controller: :tags
  end
  
end

app/models/user.rb
class User < ActiveRecord::Base
  
  has_secure_password

  has_attached_file :photo, :style => { :thumb=> "100x100#", :small => "150x150>", :medium => "300x300>", :large => "400x400>" },
    :url => "/:attachment/:id/:style/:basename.:extension",
    :path => ":rails_root/public/:attachment/:id/:style/:basename.:extension"
    
  attr_accessible :email, :password, :password_confirmation, :first_name, :last_name, :author, :admin, :photo
  
  validates_presence_of :email, :first_name, :last_name
  validates_uniqueness_of :email
  
  has_many :posts, :dependent => :destroy
  has_many :comments, :dependent => :destroy
  scope :authors, where(:author => true )
  
  def self.authenticate(email, password)
    find_by_email(email).try(:authenticate, password)
  end
  
  def is_admin?
    admin
  end
  
  def is_author?
    author
  end
  
  def name
    "#{first_name} #{last_name}"
  end
  
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  
  before_filter :require_admin
   
  # GET /users
  # GET /users.json
  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        format.html { redirect_to [:admin, @user], notice: 'User was successfully created.' }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to [:admin, @user], notice: 'User was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to admin_users_url }
      format.json { head :ok }
    end
  end
end

app/controllers/user/dashboard_controller.rb
class User::DashboardController < ApplicationController
  before_filter :require_authenticated
  def show
    
  end
end

app/controllers/user/membership_controller.rb
class User::MembershipController < ApplicationController
  
  before_filter :require_authenticated

  def show
    @user = current_user
  end
  
  def edit
    @user = current_user

  end
  
  def update
    @user = current_user
    
    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to  user_membership_info_path, notice: 'User was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end

  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController   
  # GET /users
  # GET /users.json
  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        format.html { redirect_to [:admin, @user], notice: 'User was successfully created.' }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to [:admin, @user], notice: 'User was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to admin_users_url }
      format.json { head :ok }
    end
  end
end

app/views/admin/users/_form.html.erb
<%= form_for([:admin, @user]) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label ar_t "user.email" %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label ar_t "user.password" %><br />
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label ar_t "user.password_confirmation" %><br />
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="field">
    <%= f.label ar_t "user.first_name" %><br />
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label ar_t "user.last_name" %><br />
    <%= f.text_field :last_name %>
  </div>
  <div class="field">
    <%= f.check_box :admin %>
    <%= f.label ar_t "user.admin" %>
    
  </div>
  <div class="field">
    <%= f.check_box :author %>
    <%= f.label ar_t "user.author" %>
    
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/admin/users/edit.html.erb
<%= render 'form' %>

<%= link_to (t "general.show"), [:admin, @user] %> |
<%= link_to (t "general.back"), admin_users_path %> |

app/views/admin/users/index.html.erb
<div class="panel"><%= t "allusers"%></h1>
  <div class="panel-content">
    <table>
      <tr>
        <th><%= ar_t "user.email"%></th>
        <th><%= ar_t "user.first_name"%></th>
        <th><%= ar_t "user.last_name"%></th>
        <th><%= ar_t "user.admin"%></th>
        <th><%= ar_t "user.author"%></th>
        <th></th>
        <th></th>
        <th></th>
      </tr>
      <% @users.each do |user| %>
      <tr>
        <td><%= user.email %>  </td>
        <td><%= user.first_name %></td>
        <td><%= user.last_name %></td>
        <td><%= user.admin %></td>
        <td><%= user.author %></td>
        <td><%= link_to (t "general.show"), [:admin, user] %> |</td> 
        <td><%= link_to (t "general.edit"), edit_admin_user_path(user) %> |</td> 
        <td><%= link_to (t "general.destroy"), [:admin, user], confirm: (t "general.Are you sure"), method: :delete %></td>
      </tr>
      <% end %>
    </table>
    <br />
    <%= link_to (t "general.new user"), new_admin_user_path %> 
  </div>
</div>

app/views/admin/users/new.html.erb
<h1><%= t "general.new user"%></h1>  
  
<%= form_for [:admin, @user] do |f| %>  
  <% if @user.errors.any? %>  
    <div class="error_messages">  
      <h2>Form is invalid</h2>  
      <ul>  
        <% for message in @user.errors.full_messages %>  
          <li><%= message %></li>  
        <% end %>  
      </ul>  
    </div>  
  <% end %>  
  <%= render 'form' %>
<% end %>  

app/views/admin/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b><%= ar_t "user.email"%></b>
  <%= @user.email %>
</p>

<p>
  <b><%= ar_t "user.first_name"%></b>
  <%= @user.first_name %>
</p>

<p>
  <b><%= ar_t "user.last_name"%></b>
  <%= @user.last_name %>
</p>

<p>
  <b><%= ar_t "user.admin"%></b>
  <%= @user.admin %>
</p>

<p>
  <b><%= ar_t "user.author"%></b>
  <%= @user.author %>
</p>

<%= link_to (t "general.edit"), edit_admin_user_path(@user) %> |
<%= link_to (t "general.back"), admin_users_path %> 