config/routes.rb
RayindaBlog::Application.routes.draw do

  
  mount Ckeditor::Engine => '/ckeditor'

  get "log_in" => "sessions#new", :as => "log_in"
  get "log_out" => "sessions#destroy", :as => "log_out"
  get "sign_up" => "users#new", :as => "sign_up" 
  
  get "about" => "about", controller: :about, :as => "about" 
  get "contact" => "contact", contoller: :contact, :as => "contact" 

  get "autocomplete_tag_name" => "author/posts#autocomplete_tag_name", :as => "autocomplete_tag_name"
  
  get "search" => "main#search", :as => "search"
  
  resources :sessions, :only => [:new, :create, :destroy]
  resources :users

  root :to => "main#index"
  
  namespace :admin do
    resources :posts, :users, :categories
  end
    
  namespace :user do
    resource :membership_info, only: [:show, :edit, :update], controller: :membership 
    resource :dashboard, only: [:show], controller: :dashboard
  end
  
  resources :authors, only: [:show, :index] do
    resources :posts, only: [:show, :index], controller: :author_posts
  end
  
  namespace :author do
    resources :posts, as: :myposts, controller: :posts do
      get :autocomplete_tag_name, :on => :collection
      resources :comments, only: :destroy
    end
  end
  resources :posts do
    resources :comments
  end
  resources :categories do
    resources :posts, controller: :category_posts, only: [:index, :show]
  end
  namespace :tag do
    resources :posts, only: [:index], controller: :tags
  end
  
end

app/views/admin/posts_old/_form.html.erb
<script type="text/javascript" >
   $(document).ready(function() {
      $("#markItUp").markItUp(markDownSettings);
      $("#markItUp_spot").markItUp(htmlSettings);
   });
</script>
<div class="panel">
<%= form_for([:admin, @post]) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="panel-title">
    <%= f.label t "title" %><br />
    <%= f.text_field :title %>
  </div>
  <div class="panel-title">
    <%= f.label t "category" %><br />
    <%= f.select :category_id, options_from_collection_for_select(@available_categories, 'id', 'name') %>
  </div>
  <div class="panel-title">
    <%= f.label t "post" %><br />
    <div class="markDownEdit">
      <%= f.text_area :body, :id => "markItUp" %>
    </div>
  </div>
  <div class="panel-title">
    <%= f.label t "spot" %><br />
    <%= f.text_area :spot, :id => "markItUp_spot" %>
  </div>
  <div class="panel-title">
    <%= f.label t "published" %>
    <%= f.check_box :published %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
  <% end %>
</div>

app/views/admin/posts_old/edit.html.erb
<%= render 'form' %>


<%= link_to (t "general.show"), [:admin, @post] %> |
<%= link_to (t "general.back"), admin_posts_path %>

app/views/admin/posts_old/index.html.erb
<div class="articles">
<% @posts.each do |post| %>
	<div class="article">
	  <div class="article-title">
      <span class="article_cat"><%= link_to post.category.try(:name), category_posts_path(post.category) %></span>
	    <h2><%= link_to post.title, [:admin, post] %></h2>
	  </div>
		<div class="article-content">
		  <p>
		  <%= post.spot.html_safe %>
		  </p>
		</div>
    	  <div class="article-cdt">
			<div class="date"><%= post.published_at.try(:strftime, '%d-%m-%y') %></div>
			<div class="tag">
        <ul>
        <% post.tags.each do |tag|%>
            <li>
            <%= link_to tag.name, tag_posts_path(:tag => tag.name) %>
          </li>
          <% end %>
      </ul>
      </div>
	    <div class="author"><%= link_to post.user.name, author_posts_path(post.user_id) %></div>
    </div>
	</div>
<% end %>
</div>

<div class="pgnt">
	<div class="pgntt">
    <div class="tag"><%= paginate @posts%></div>
  </div>
</div>

app/views/admin/posts_old/show.html.erb
<div class="articles">
  <div class="article">
	  <div class="article-title">
      <span class="article_cat"><%= link_to @post.category.try(:name), category_posts_path(@post.category) %></span>
	    <h2><%= @post.title %></h2>
	  </div>
		<div class="article-content">
		  <p>
		  <%= markdown(@post.rendered_body) %>
		  </p>
		</div>
        <div class="article-cdt">
			<div class="date"><%= @post.published_at.try(:strftime, '%d-%m-%y') %></div>
			<div class="tag">
        <ul>
        <% @post.tags.each do |tag|%>
            <li>
            <%= link_to tag.name, tag_posts_path(:tag => tag.name) %>
            </li>
        <% end %>
      </ul></div>
          <div class="author"><%= link_to @post.user.name, author_posts_path(@post.user_id), :class => "au" %></div>
          <span class="article-comment"><%= link_to (t "general.add", :class => (t "comment").downcase), author_post_path(@post.user, @post) %></span>
	  </div>

    


</div>
 <div class="admlinks">
   <ul>
    <li><%= link_to (t "general.edit"), edit_admin_post_path(@post) %></li>
    <li><%= link_to (t "general.back"), admin_posts_path %></li>
    <li><%= link_to (t "general.destroy"), admin_post_path(@post),confirm: (t "general.Are you sure"),
            :method => :delete %></li>
 </ul>
 </div>
</div>